version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  reviewers:
  - dvelasquez
  versioning-strategy: increase
  ignore:
  - dependency-name: snyk
    versions:
    - 1.440.1
    - 1.486.0
    - 1.503.0
    - 1.511.0
    - 1.530.0
    - 1.564.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.19.0
  - dependency-name: "@rollup/plugin-html"
    versions:
    - 0.2.2
  - dependency-name: svelte-preprocess
    versions:
    - 4.6.5
