sudo: false
os: linux
language: node_js
node_js: '12'
cache:
  directories:
    - ~/.nvm
    - node_modules
before_install:
  - git remote set-url origin "https://${GITHUB_API_TOKEN}@github.com/dvelasquez/lighthouse-viewer.git" > /dev/null 2>&1
  - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
install:
  - npm install
  - npm run lint
  - npm run lerna:build
after_success:
  - bash ci/success.sh
