packages:
  - 'packages/lighthouse-viewer'
  - 'packages/react2-lighthouse-viewer'
  - 'packages/svelte-lighthouse-viewer'
  - 'packages/vue-lighthouse-viewer'
  - 'web/lighthouse-viewer'
  - 'examples/create-react-app'

link-workspace-packages: true